### ISSUE TITLE
serverless yml environment not available in js/ts files in a react project

### ISSUE THREAD

**Issue by s1mrankaur** [tgfischer/serverless-build-client#18]
The only variables I am seeing under process.env are 
"Env": "Production",
"Public URL":""

My serverless.yml looks like  following:
```

service: vlncc-frontend

plugins:
  - serverless-finch
  - serverless-build-client

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "sandbox"}
  region: ${opt:region, "us-west-2"}
  profile: ${opt:profile, 'sandbox'}


  environment:
    REACT_APP_TENANT_MANAGEMENT_ENDPOINT: ${cf:tenant-mgmt-service-${self:provider.stage}.ServiceEndpoint}


custom:
  client:
    bucketName: frontend-${self:provider.stage}-website
    distributionFolder: build/
    indexDocument: index.html
    errorDocument: index.html
```

In the .js file, I  tried:

`process.env. REACT_APP_TENANT_MANAGEMENT_ENDPOINT `but there is no such variable defined. Why is that? How do I fix it?
